CREATE DATABASE IF NOT EXISTS mixkit_records
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE mixkit_records;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  instrumento VARCHAR(120) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
